
module.exports = {
	CHANGE_SLIDE: 'CHANGE_SLIDE',
	CHANGE_HERO_SLIDE: 'CHANGE_HERO_SLIDE',
	COOPERATE: 'COOPERATE',
	FORM_COOPERATE_TOGGLE: 'FORM_COOPERATE_TOGGLE',
	FORM_APPOINTMENT_TOGGLE: 'FORM_APPOINTMENT_TOGGLE',
	COOPERATE_COUNTER_CHANGE: 'COOPERATE_COUNTER_CHANGE',
	SELECT_SERVICE: 'SELECT_SERVICE',
	SERVICE_SELECT_TOGGLE: 'SERVICE_SELECT_TOGGLE',
	INIT_INPUTS: 'INIT_INPUTS',
	SUBMIT_FORM: 'SUBMIT_FORM',
	NAV_MOBILE_TOGGLE: 'NAV_MOBILE_TOGGLE',
	SCROLL_TO_SECTION: 'SCROLL_TO_SECTION',
};